import React, { useState } from 'react';
import { AnalysisResponse, ResultTab, IndividualAnalysis, SummaryRow } from '../types';
import { BookOpen, Table, Network, Download, ChevronRight } from 'lucide-react';
import { jsPDF } from "jspdf";

interface AnalysisViewProps {
  data: AnalysisResponse;
  topic: string;
  onReset: () => void;
}

export const AnalysisView: React.FC<AnalysisViewProps> = ({ data, topic, onReset }) => {
  const [activeTab, setActiveTab] = useState<ResultTab>(ResultTab.INDIVIDUAL);

  const getRatingColor = (rating: number) => {
    if (rating >= 85) return 'text-green-600 bg-green-50 border-green-200';
    if (rating >= 60) return 'text-blue-600 bg-blue-50 border-blue-200';
    if (rating >= 30) return 'text-yellow-600 bg-yellow-50 border-yellow-200';
    return 'text-red-600 bg-red-50 border-red-200';
  };

  const getUtilityBadge = (utility: string) => {
    switch (utility) {
      case 'High': return 'bg-green-100 text-green-800 border-green-200';
      case 'Medium': return 'bg-blue-100 text-blue-800 border-blue-200';
      case 'Low': return 'bg-slate-100 text-slate-800 border-slate-200';
      default: return 'bg-gray-100 text-gray-800';
    }
  };

  const handleExport = () => {
    const doc = new jsPDF();
    const pageWidth = doc.internal.pageSize.getWidth();
    const pageHeight = doc.internal.pageSize.getHeight();
    const margin = 20;
    const maxLineWidth = pageWidth - margin * 2;
    let cursorY = 20;

    const checkAddPage = (heightNeeded: number) => {
      if (cursorY + heightNeeded > pageHeight - margin) {
        doc.addPage();
        cursorY = 20;
      }
    };

    const addHeading = (text: string, size = 16, isSerif = true) => {
      doc.setFont(isSerif ? "times" : "helvetica", "bold");
      doc.setFontSize(size);
      checkAddPage(size / 2 + 5);
      doc.text(text, margin, cursorY);
      cursorY += size * 0.5 + 4; // Spacing after heading
      doc.setFont("helvetica", "normal"); // Reset to default sans
    };

    const addText = (text: string, size = 10, isBold = false) => {
      if (!text) return;
      doc.setFont("helvetica", isBold ? "bold" : "normal");
      doc.setFontSize(size);
      
      const splitText = doc.splitTextToSize(text, maxLineWidth);
      const lineHeight = size * 0.45; // Approx mm height per line
      const blockHeight = splitText.length * lineHeight;
      
      checkAddPage(blockHeight + 2);
      doc.text(splitText, margin, cursorY);
      cursorY += blockHeight + 3; // Spacing after paragraph
    };

    const addSeparator = () => {
       cursorY += 5;
       checkAddPage(10);
       doc.setDrawColor(200, 200, 200);
       doc.line(margin, cursorY, pageWidth - margin, cursorY);
       cursorY += 10;
    };

    // --- PDF CONTENT GENERATION ---

    // Title Page Header
    doc.setFont("times", "bold");
    doc.setFontSize(22);
    doc.text("Systematic Literature Review", margin, cursorY);
    cursorY += 12;

    doc.setFont("helvetica", "normal");
    doc.setFontSize(10);
    doc.setTextColor(100);
    doc.text(`Generated by ScholarSync on ${new Date().toLocaleDateString()}`, margin, cursorY);
    doc.setTextColor(0);
    cursorY += 15;

    // Research Topic Section
    doc.setDrawColor(226, 232, 240); // Slate-200
    doc.setFillColor(248, 250, 252); // Slate-50
    doc.rect(margin, cursorY, maxLineWidth, 25, 'FD');
    
    doc.setFont("times", "bold");
    doc.setFontSize(12);
    doc.text("Research Topic:", margin + 5, cursorY + 8);
    
    doc.setFont("helvetica", "italic");
    doc.setFontSize(11);
    const topicLines = doc.splitTextToSize(topic, maxLineWidth - 10);
    doc.text(topicLines, margin + 5, cursorY + 16);
    cursorY += 35;

    // 1. Summary Overview
    addHeading("1. Summary Overview", 14);
    
    data.summaryTable.forEach((row) => {
        checkAddPage(20);
        doc.setFont("helvetica", "bold");
        doc.setFontSize(10);
        doc.text(`• ${row.article}`, margin, cursorY);
        const ratingWidth = doc.getTextWidth(`• ${row.article}`);
        
        doc.setFont("helvetica", "normal");
        doc.setFontSize(9);
        doc.setTextColor(80);
        doc.text(` | Rating: ${row.rating} | Utility: ${row.utility}`, margin + ratingWidth + 2, cursorY);
        doc.setTextColor(0);
        
        cursorY += 5;
        
        doc.setFontSize(10);
        const conclusionLines = doc.splitTextToSize(row.coreConclusion, maxLineWidth - 5);
        checkAddPage(conclusionLines.length * 4.5);
        doc.text(conclusionLines, margin + 5, cursorY);
        cursorY += (conclusionLines.length * 4.5) + 4;
    });

    addSeparator();

    // 2. Synthesis Matrix
    addHeading("2. Synthesis Matrix", 14);

    const addSynthesisSection = (title: string, items: string[]) => {
        if (items.length === 0) return;
        
        doc.setFont("helvetica", "bold");
        doc.setFontSize(11);
        checkAddPage(10);
        doc.text(title, margin, cursorY);
        cursorY += 6;
        
        doc.setFont("helvetica", "normal");
        doc.setFontSize(10);
        
        items.forEach(item => {
            const bullet = "• ";
            const lines = doc.splitTextToSize(bullet + item, maxLineWidth);
            checkAddPage(lines.length * 5);
            doc.text(lines, margin, cursorY);
            cursorY += (lines.length * 5) + 2;
        });
        cursorY += 5;
    };

    addSynthesisSection("Common Themes", data.synthesisMatrix.commonThemes);
    addSynthesisSection("Divergent Results", data.synthesisMatrix.divergentResults);
    addSynthesisSection("Research Gaps", data.synthesisMatrix.researchGaps);

    addSeparator();

    // 3. Individual Analysis
    addHeading("3. Deep Individual Analysis", 14);

    data.individualAnalyses.forEach((item, index) => {
        if (index > 0) addSeparator();
        
        checkAddPage(20);
        doc.setFont("times", "bold");
        doc.setFontSize(12);
        const titleLines = doc.splitTextToSize(item.title, maxLineWidth);
        doc.text(titleLines, margin, cursorY);
        cursorY += (titleLines.length * 5) + 2;

        doc.setFont("helvetica", "normal");
        doc.setFontSize(9);
        doc.setTextColor(80);
        doc.text(`${item.authors} (${item.year}) | Relevance: ${item.relevanceRating}/100`, margin, cursorY);
        doc.setTextColor(0);
        cursorY += 8;

        const addSubSection = (label: string, content: string) => {
            doc.setFont("helvetica", "bold");
            doc.setFontSize(9);
            checkAddPage(5);
            doc.text(label, margin, cursorY);
            cursorY += 4;
            addText(content, 10);
        };

        addSubSection("Methodological Summary:", item.methodologicalSummary);
        addSubSection("Key Contributions:", item.keyContributions);
        addSubSection("Rating Justification:", item.ratingJustification);
        
        // Thesis Integration (Highlighted)
        checkAddPage(15);
        doc.setDrawColor(252, 211, 77); // Amber-300
        doc.setFillColor(255, 251, 235); // Amber-50
        
        // Calculate height needed
        doc.setFont("helvetica", "italic");
        doc.setFontSize(10);
        const integrationLines = doc.splitTextToSize(item.thesisIntegration, maxLineWidth - 10);
        const boxHeight = (integrationLines.length * 4.5) + 12;
        
        checkAddPage(boxHeight);
        doc.rect(margin, cursorY, maxLineWidth, boxHeight, 'FD');
        
        doc.setFont("helvetica", "bold");
        doc.setFontSize(9);
        doc.setTextColor(180, 83, 9); // Amber-700
        doc.text("Thesis Integration:", margin + 5, cursorY + 6);
        
        doc.setFont("helvetica", "italic");
        doc.setFontSize(10);
        doc.setTextColor(0);
        doc.text(integrationLines, margin + 5, cursorY + 12);
        
        cursorY += boxHeight + 8;
    });

    // Save
    doc.save(`ScholarSync_Report_${new Date().toISOString().slice(0,10)}.pdf`);
  };

  return (
    <div className="w-full max-w-6xl mx-auto p-4 md:p-8 animate-fade-in">
      {/* Header */}
      <div className="flex flex-col md:flex-row justify-between items-start md:items-center mb-8 gap-4 border-b border-gray-200 pb-6">
        <div>
          <h2 className="text-2xl font-serif font-bold text-academic-900">Systematic Literature Review</h2>
          <p className="text-academic-500 mt-1">Research Topic: <span className="font-semibold text-academic-700">{topic}</span></p>
        </div>
        <div className="flex gap-3">
            <button 
                onClick={onReset}
                className="px-4 py-2 text-sm text-academic-600 hover:text-academic-900 font-medium transition-colors"
            >
                Start New Analysis
            </button>
            <button 
                className="flex items-center gap-2 px-4 py-2 bg-academic-800 text-white rounded-lg hover:bg-academic-900 transition-colors shadow-sm"
                onClick={handleExport}
            >
                <Download size={16} />
                Export PDF
            </button>
        </div>
      </div>

      {/* Tabs */}
      <div className="flex flex-wrap gap-2 mb-8 bg-academic-50 p-1.5 rounded-xl w-fit">
        <button
          onClick={() => setActiveTab(ResultTab.INDIVIDUAL)}
          className={`flex items-center gap-2 px-4 py-2.5 rounded-lg text-sm font-medium transition-all ${
            activeTab === ResultTab.INDIVIDUAL
              ? 'bg-white text-academic-900 shadow-sm'
              : 'text-academic-500 hover:text-academic-700 hover:bg-academic-100/50'
          }`}
        >
          <BookOpen size={16} />
          Deep Analysis
        </button>
        <button
          onClick={() => setActiveTab(ResultTab.SUMMARY)}
          className={`flex items-center gap-2 px-4 py-2.5 rounded-lg text-sm font-medium transition-all ${
            activeTab === ResultTab.SUMMARY
              ? 'bg-white text-academic-900 shadow-sm'
              : 'text-academic-500 hover:text-academic-700 hover:bg-academic-100/50'
          }`}
        >
          <Table size={16} />
          Summary Table
        </button>
        <button
          onClick={() => setActiveTab(ResultTab.SYNTHESIS)}
          className={`flex items-center gap-2 px-4 py-2.5 rounded-lg text-sm font-medium transition-all ${
            activeTab === ResultTab.SYNTHESIS
              ? 'bg-white text-academic-900 shadow-sm'
              : 'text-academic-500 hover:text-academic-700 hover:bg-academic-100/50'
          }`}
        >
          <Network size={16} />
          Synthesis Matrix
        </button>
      </div>

      {/* Content Area */}
      <div className="min-h-[60vh]">
        {activeTab === ResultTab.INDIVIDUAL && (
          <div className="grid grid-cols-1 gap-6">
            {data.individualAnalyses.map((item, idx) => (
              <div key={idx} className="bg-white rounded-xl border border-gray-200 shadow-sm overflow-hidden hover:shadow-md transition-shadow">
                <div className="p-6 border-b border-gray-100 bg-gray-50/50 flex flex-col md:flex-row justify-between gap-4">
                  <div>
                    <h3 className="text-xl font-serif font-bold text-academic-900 mb-1">{item.title}</h3>
                    <div className="text-sm text-academic-500 flex items-center gap-2">
                        <span>{item.authors}</span>
                        <span className="w-1 h-1 rounded-full bg-academic-300"></span>
                        <span>{item.year}</span>
                    </div>
                  </div>
                  <div className={`flex items-center justify-center px-4 py-2 rounded-lg border text-lg font-bold h-fit whitespace-nowrap ${getRatingColor(item.relevanceRating)}`}>
                    {item.relevanceRating} / 100
                  </div>
                </div>
                
                <div className="p-6 grid grid-cols-1 lg:grid-cols-3 gap-8">
                    <div className="lg:col-span-2 space-y-6">
                        <Section title="Methodological Summary" content={item.methodologicalSummary} />
                        <Section title="Key Contributions" content={item.keyContributions} />
                    </div>
                    <div className="space-y-6">
                         <div className="bg-academic-50 rounded-lg p-4 border border-academic-100">
                             <h4 className="text-xs font-bold uppercase tracking-wider text-academic-500 mb-2">Rating Justification</h4>
                             <p className="text-sm text-academic-700 leading-relaxed">{item.ratingJustification}</p>
                         </div>
                         <div className="bg-amber-50 rounded-lg p-4 border border-amber-100">
                             <h4 className="text-xs font-bold uppercase tracking-wider text-amber-600 mb-2">Thesis Integration</h4>
                             <p className="text-sm text-academic-800 leading-relaxed italic">"{item.thesisIntegration}"</p>
                         </div>
                    </div>
                </div>
              </div>
            ))}
          </div>
        )}

        {activeTab === ResultTab.SUMMARY && (
          <div className="bg-white rounded-xl border border-gray-200 shadow-sm overflow-hidden">
            <div className="overflow-x-auto">
              <table className="w-full text-left border-collapse">
                <thead>
                  <tr className="bg-academic-50 border-b border-academic-200">
                    <th className="py-4 px-6 font-semibold text-sm text-academic-700 uppercase tracking-wider w-1/4">Article</th>
                    <th className="py-4 px-6 font-semibold text-sm text-academic-700 uppercase tracking-wider w-24">Rating</th>
                    <th className="py-4 px-6 font-semibold text-sm text-academic-700 uppercase tracking-wider">Core Conclusion</th>
                    <th className="py-4 px-6 font-semibold text-sm text-academic-700 uppercase tracking-wider w-32">Utility</th>
                  </tr>
                </thead>
                <tbody className="divide-y divide-gray-100">
                  {data.summaryTable.map((row, idx) => (
                    <tr key={idx} className="hover:bg-gray-50/80 transition-colors">
                      <td className="py-4 px-6 text-sm font-medium text-academic-900">{row.article}</td>
                      <td className="py-4 px-6 text-sm">
                        <span className={`font-bold ${row.rating >= 60 ? 'text-academic-800' : 'text-academic-500'}`}>{row.rating}</span>
                      </td>
                      <td className="py-4 px-6 text-sm text-academic-600 leading-relaxed">{row.coreConclusion}</td>
                      <td className="py-4 px-6 text-sm">
                        <span className={`inline-flex items-center px-2.5 py-0.5 rounded-full text-xs font-medium border ${getUtilityBadge(row.utility)}`}>
                          {row.utility}
                        </span>
                      </td>
                    </tr>
                  ))}
                </tbody>
              </table>
            </div>
          </div>
        )}

        {activeTab === ResultTab.SYNTHESIS && (
          <div className="grid grid-cols-1 lg:grid-cols-3 gap-6">
             <SynthesisCard 
                title="Common Themes" 
                items={data.synthesisMatrix.commonThemes} 
                icon={<div className="w-2 h-2 rounded-full bg-blue-500"></div>}
                colorClass="border-blue-200 bg-blue-50/30"
            />
             <SynthesisCard 
                title="Divergent Results" 
                items={data.synthesisMatrix.divergentResults} 
                icon={<div className="w-2 h-2 rounded-full bg-orange-500"></div>}
                colorClass="border-orange-200 bg-orange-50/30"
            />
             <SynthesisCard 
                title="Research Gaps" 
                items={data.synthesisMatrix.researchGaps} 
                icon={<div className="w-2 h-2 rounded-full bg-purple-500"></div>}
                colorClass="border-purple-200 bg-purple-50/30"
            />
          </div>
        )}
      </div>
    </div>
  );
};

const Section: React.FC<{ title: string; content: string }> = ({ title, content }) => (
    <div>
        <h4 className="text-sm font-bold uppercase tracking-wider text-academic-400 mb-2">{title}</h4>
        <p className="text-academic-800 leading-relaxed font-serif text-sm md:text-base">{content}</p>
    </div>
);

const SynthesisCard: React.FC<{ title: string; items: string[]; icon: React.ReactNode; colorClass: string }> = ({ title, items, icon, colorClass }) => (
    <div className={`bg-white rounded-xl border shadow-sm p-6 ${colorClass}`}>
        <h3 className="text-lg font-bold text-academic-900 mb-4 flex items-center gap-2">
            {title}
        </h3>
        <ul className="space-y-3">
            {items.map((item, idx) => (
                <li key={idx} className="flex items-start gap-3 text-academic-700 text-sm leading-relaxed">
                    <span className="mt-2 shrink-0">{icon}</span>
                    <span>{item}</span>
                </li>
            ))}
        </ul>
    </div>
);